[package]
name = "play"
version = "1.0.0"
authors = []

[addresses]
play = "_"

[dev-addresses]
play = "0x1cce31ab18c8f81e92c0aa3c26a6a1fc7a5bbbda50f80c4f1ad7d3e9eb04242d"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
