[package]
name = "play"
version = "1.0.0"

[addresses]
play = "_"
aptos_framework = "0x1"

[dev-addresses]
play = "0x7d2a5f5f1a1bd409a4f6dc6e44045ba64de71f756b793480b46e736944bbde27"

[dependencies]

[dev-dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", rev = "mainnet", subdir = "aptos-framework", addr_subst = { aptos_framework = "0x1" } }
